version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: web
    ports:
      - "3000:3000"

  second:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: second
    ports:
      - "3001:3000"
